changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking change
    - title: New Features
      labels:
        - feature      
    - title: Other Changes
      labels:
        - "*"
